name: Upload Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.108.0"
          extended: true

      - name: Build
        run: hugo --minify --baseURL https://wouter.toorren.net/

      - name: Deploy to Other Repository
        uses: actions/checkout@v2
        with:
          repository: TorreiroW/woutersite-live # Vervang dit door de naam van de andere repository
          token: ${{ secrets.WEBSITE_SYNC_PAT}}

      - name: Commit and push changes
        run: |
          ls -latr
          cd public
          ls -latr
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Deploy Hugo Build Output"
          git push
